import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <div className="flex h-screen">
          {/* Sidebar */}
          <aside className="w-64 bg-gray-900 text-white flex flex-col py-6 px-4 space-y-8">
            {/* Logo */}
            <div className="flex items-center gap-2 mb-6">
              <Image width={32} height={32} src="/window.svg" alt="Logo" className="w-8 h-8" />
              <span className="font-bold text-2xl text-red-600">CloneTube</span>
            </div>
            {/* Categories */}
            <div>
              <h2 className="text-lg font-semibold mb-2">Categories</h2>
              <ul className="space-y-2">
                <li><button className="w-full text-left px-2 py-1 rounded hover:bg-gray-800">Home</button></li>
                <li><button className="w-full text-left px-2 py-1 rounded hover:bg-gray-800">Trending</button></li>
                <li><button className="w-full text-left px-2 py-1 rounded hover:bg-gray-800">Music</button></li>
                <li><button className="w-full text-left px-2 py-1 rounded hover:bg-gray-800">Gaming</button></li>
                <li><button className="w-full text-left px-2 py-1 rounded hover:bg-gray-800">News</button></li>
              </ul>
            </div>
            {/* Subscriptions */}
            <div>
              <h2 className="text-lg font-semibold mb-2">Subscriptions</h2>
              <ul className="space-y-2">
                <li><button className="w-full text-left px-2 py-1 rounded hover:bg-gray-800">Vention</button></li>
                <li><button className="w-full text-left px-2 py-1 rounded hover:bg-gray-800">React Channel</button></li>
                <li><button className="w-full text-left px-2 py-1 rounded hover:bg-gray-800">Next.js Tutorials</button></li>
              </ul>
            </div>
          </aside>
          {/* Main Content */}
          <div className="flex-1 flex flex-col">
            {/* Top Navigation */}
            <header className="flex items-center justify-between px-8 py-4 bg-white shadow">
              {/* Left: Logo (for mobile) */}
              <div className="flex items-center gap-4 sm:hidden">
                <Image width={32} height={32} src="/window.svg" alt="Logo" className="w-8 h-8" />
                <span className="font-bold text-xl text-red-600">YouTube</span>
              </div>
              {/* Center: Search Bar */}
              <div className="flex-1 flex justify-center">
                <div className="flex items-center w-full max-w-xl">
                  <input type="text" placeholder="Search" className="border border-gray-300 rounded-l-full px-4 py-2 w-full focus:outline-none focus:ring-2 focus:ring-red-500" />
                  <button className="bg-gray-100 border border-gray-300 rounded-r-full px-4 py-2 hover:bg-gray-200">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><circle cx="11" cy="11" r="8" /><path d="M21 21l-4.35-4.35" /></svg>
                  </button>
                </div>
              </div>
              {/* Right: Profile Icon */}
              <div className="flex items-center gap-4">
                <button className="hover:bg-gray-100 p-2 rounded-full" title="Upload">
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M4 17v2a2 2 0 002 2h12a2 2 0 002-2v-2" /><path d="M7 9l5-5 5 5" /><path d="M12 4v12" /></svg>
                </button>
                <button className="hover:bg-gray-100 p-2 rounded-full" title="Notifications">
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
                </button>
                <Image src="/file.svg" alt="User" width={32} height={32} className="w-8 h-8 rounded-full border" />
              </div>
            </header>
            {/* Page Content */}
            <main className="flex-1 overflow-y-auto bg-gray-50 p-8">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
